### ISSUE TITLE
Default generated unit test for a Java function doesn't compile

### ISSUE THREAD

**Issue by SCWells72** [forcedotcom/sf-fx-sdk-java#108]
I just spoke with @julianduque about this problem and he suggested I file an issue here, so hopefully it's the right place. 

It looks like the auto-generated unit test for a Java function is no longer valid. It includes:
```
Record firstRecord = mock(Record.class);
when(firstRecord.getStringField("Id")).thenReturn(Optional.of("5003000000D8cuIQAA"));
when(firstRecord.getStringField("Name")).thenReturn(Optional.of("Account One, inc."));

Record secondRecord = mock(Record.class);
when(secondRecord.getStringField("Id")).thenReturn(Optional.of("6003000000D8cuIQAA"));
when(secondRecord.getStringField("Name")).thenReturn(Optional.of("Account Two, inc."));

when(mockResult.getRecords()).thenReturn(Arrays.asList(firstRecord, secondRecord));
```
which yields the following compilation error on the last line for `thenReturn`:
```
java: no suitable method found for thenReturn(java.util.List<com.salesforce.functions.jvm.sdk.data.Record>)
    method org.mockito.stubbing.OngoingStubbing.thenReturn(java.util.List<com.salesforce.functions.jvm.sdk.data.RecordWithSubQueryResults>) is not applicable
      (argument mismatch; inference variable T has incompatible bounds
          equality constraints: com.salesforce.functions.jvm.sdk.data.RecordWithSubQueryResults
          lower bounds: com.salesforce.functions.jvm.sdk.data.Record)
```
The fix is to change the type of `firstRecord` and `secondRecord` to be `RecordWithSubQueryResults`.

I know this is a relatively minor thing overall, but I can easily see someone trying out Java functions for the first time being frustrated that the default generated unit test won't compile or run.

Note that this is using the following versions:
```
$ sfdx --version
sfdx-cli/7.183.1 win32-x64 node-v18.12.1
$ sf --version
@salesforce/cli/1.60.2 win32-x64 node-v18.12.1
$ sf plugins
functions 1.17.3
```

**Comment by colincasey** [comment]
thanks @SCWells72.  the bug with the code you're referring to is located in another repository that handles the template generation process but i'll see that it gets addressed.

**Comment by colincasey** [comment]
@SCWells72 this issue has been fixed in the latest `sf` [CLI release candidate](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_rc.htm) ([v1.63.1](https://www.npmjs.com/package/@salesforce/cli/v/1.63.1)) and will be included in the next weekly release.
